---
abstract: 'Pragma to exempt a module from loading'
author:
  - 'Anno Siegel <anno5@mac.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: loading
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0
version: 1.01
